import streamlit as st
from sentence_transformers import SentenceTransformer
import numpy as np
import pandas as pd
import json


sdg_data = [
    {
        "sdg_no": 1,
        "title": "No Poverty",
        "content": "End poverty in all its forms everywhere.",
        "targets": [
            {"target_no": "1.1", "description": "By 2030, eradicate extreme poverty for all people everywhere, currently measured as people living on less than $1.25 a day."}
        ],
        "indicators": [
            {"indicator_no": "1.1.1", "description": "Africa"},
            {"indicator_no": "1.1.2", "description": "Basic services"},
            {"indicator_no": "1.1.3", "description": "Class"},
            {"indicator_no": "1.1.4", "description": "Developing countries"},
            {"indicator_no": "1.1.5", "description": "Disadvantaged"},
            {"indicator_no": "1.1.6", "description": "Economic resources"},
            {"indicator_no": "1.1.7", "description": "End poverty"},
            {"indicator_no": "1.1.8", "description": "Environment"},
            {"indicator_no": "1.1.9", "description": "Equality"},
            {"indicator_no": "1.1.10", "description": "Extreme poverty"},
            {"indicator_no": "1.1.11", "description": "Financial inclusion"},
            {"indicator_no": "1.1.12", "description": "Income"},
            {"indicator_no": "1.1.13", "description": "Income equality"},
            {"indicator_no": "1.1.14", "description": "Microfinance"},
            {"indicator_no": "1.1.15", "description": "Non-discrimination"},
            {"indicator_no": "1.1.16", "description": "Poor"},
            {"indicator_no": "1.1.17", "description": "Poor and vulnerable"},
            {"indicator_no": "1.1.18", "description": "Poverty"},
            {"indicator_no": "1.1.19", "description": "Poverty eradication"},
            {"indicator_no": "1.1.20", "description": "Poverty line"},
            {"indicator_no": "1.1.21", "description": "Quality of Life"},
            {"indicator_no": "1.1.22", "description": "Resources"},
            {"indicator_no": "1.1.23", "description": "Social protection"},
            {"indicator_no": "1.1.24", "description": "Social protection systems"},
            {"indicator_no": "1.1.25", "description": "Sustainable"},
            {"indicator_no": "1.1.26", "description": "Third World"},
            {"indicator_no": "1.1.27", "description": "Vulnerable"},
            {"indicator_no": "1.1.28", "description": "Wealth distribution"}
        ]
    },
    {
        "sdg_no": 2,
        "title": "Zero Hunger",
        "content": "End hunger, achieve food security and improved nutrition and promote sustainable agriculture.",
        "targets": [
            {"target_no": "2.1", "description": "By 2030, end hunger and ensure access by all people, in particular the poor and people in vulnerable situations, including infants, to safe, nutritious and sufficient food all year round."}
        ],
        "indicators": [
            {"indicator_no": "2.1.1", "description": "Agricultural Orientation index"},
            {"indicator_no": "2.1.2", "description": "Agricultural productivity"},
            {"indicator_no": "2.1.3", "description": "Agriculture"},
            {"indicator_no": "2.1.4", "description": "Consume"},
            {"indicator_no": "2.1.5", "description": "Crop diversity"},
            {"indicator_no": "2.1.6", "description": "Crops"},
            {"indicator_no": "2.1.7", "description": "Doha Development Round"},
            {"indicator_no": "2.1.8", "description": "Doha Round"},
            {"indicator_no": "2.1.9", "description": "End hunger"},
            {"indicator_no": "2.1.10", "description": "Environment"},
            {"indicator_no": "2.1.11", "description": "Food"},
            {"indicator_no": "2.1.12", "description": "Food gap"},
            {"indicator_no": "2.1.13", "description": "Food production"},
            {"indicator_no": "2.1.14", "description": "Food reserves"},
            {"indicator_no": "2.1.15", "description": "Food Security"},
            {"indicator_no": "2.1.16", "description": "Genetic diversity"},
            {"indicator_no": "2.1.17", "description": "Genetic diversity of seeds"},
            {"indicator_no": "2.1.18", "description": "Genetics"},
            {"indicator_no": "2.1.19", "description": "Hunger"},
            {"indicator_no": "2.1.20", "description": "Hungry people"},
            {"indicator_no": "2.1.21", "description": "Improved nutrition"},
            {"indicator_no": "2.1.22", "description": "Innovations and health"},
            {"indicator_no": "2.1.23", "description": "Legumes"},
            {"indicator_no": "2.1.24", "description": "Maize"},
            {"indicator_no": "2.1.25", "description": "Malnourished"},
            {"indicator_no": "2.1.26", "description": "Malnutrition"},
            {"indicator_no": "2.1.27", "description": "Nutrition"},
            {"indicator_no": "2.1.28", "description": "Nutritional needs"},
            {"indicator_no": "2.1.29", "description": "Nutritious"},
            {"indicator_no": "2.1.30", "description": "Poverty"},
            {"indicator_no": "2.1.31", "description": "Produce"},
            {"indicator_no": "2.1.32", "description": "Productivity"},
            {"indicator_no": "2.1.33", "description": "Quality of life"},
            {"indicator_no": "2.1.34", "description": "Resilient agriculture"},
            {"indicator_no": "2.1.35", "description": "Rural infrastructure"},
            {"indicator_no": "2.1.36", "description": "Small-scale food producers"},
            {"indicator_no": "2.1.37", "description": "Stunted growth"},
            {"indicator_no": "2.1.38", "description": "Stunting"},
            {"indicator_no": "2.1.39", "description": "Sufficient food"},
            {"indicator_no": "2.1.40", "description": "Sustainable"},
            {"indicator_no": "2.1.41", "description": "Sustainable agriculture"},
            {"indicator_no": "2.1.42", "description": "Sustainable food production"},
            {"indicator_no": "2.1.43", "description": "Trade diversity"},
            {"indicator_no": "2.1.44", "description": "Trade restrictions"},
            {"indicator_no": "2.1.45", "description": "Under nourished"},
            {"indicator_no": "2.1.46", "description": "Undernourished"},
            {"indicator_no": "2.1.47", "description": "Wasting"},
            {"indicator_no": "2.1.48", "description": "World’s hungry"}
        ]
    },
    {
        "sdg_no": 3,
        "title": "Good Health and Well-being",
        "content": "Ensure healthy lives and promote well-being for all at all ages.",
        "targets": [
            {"target_no": "3.1", "description": "By 2030, reduce the global maternal mortality ratio to less than 70 per 100,000 live births."}
        ],
        "indicators": [
            {"indicator_no": "3.1.1", "description": "Access to clean water and sanitation"},
            {"indicator_no": "3.1.2", "description": "Affordable medicines"},
            {"indicator_no": "3.1.3", "description": "AIDS"},
            {"indicator_no": "3.1.4", "description": "Air contamination"},
            {"indicator_no": "3.1.5", "description": "Air pollution"},
            {"indicator_no": "3.1.6", "description": "Alcohol abuse"},
            {"indicator_no": "3.1.7", "description": "Antenatal care"},
            {"indicator_no": "3.1.8", "description": "Antiretroviral"},
            {"indicator_no": "3.1.9", "description": "Antiretroviral therapy"},
            {"indicator_no": "3.1.10", "description": "Biomedical"},
            {"indicator_no": "3.1.11", "description": "Bodily autonomy"},
            {"indicator_no": "3.1.12", "description": "Child deaths"},
            {"indicator_no": "3.1.13", "description": "Contraceptive use"},
            {"indicator_no": "3.1.14", "description": "Death rate"},
            {"indicator_no": "3.1.15", "description": "Dental"},
            {"indicator_no": "3.1.16", "description": "Disability and family support"},
            {"indicator_no": "3.1.17", "description": "Disability and inclusion"},
            {"indicator_no": "3.1.18", "description": "Disability and politics of location"},
            {"indicator_no": "3.1.19", "description": "Diseases"},
            {"indicator_no": "3.1.20", "description": "Family planning"},
            {"indicator_no": "3.1.21", "description": "Health"},
            {"indicator_no": "3.1.22", "description": "Health in resource-constrained settings"},
            {"indicator_no": "3.1.23", "description": "Health worker density"},
            {"indicator_no": "3.1.24", "description": "Healthy"},
            {"indicator_no": "3.1.25", "description": "Healthy lives"},
            {"indicator_no": "3.1.26", "description": "Hepatitis"},
            {"indicator_no": "3.1.27", "description": "HIV"},
            {"indicator_no": "3.1.28", "description": "Improving mortality"},
            {"indicator_no": "3.1.29", "description": "Increasing life expectancy"},
            {"indicator_no": "3.1.30", "description": "Indigenous"},
            {"indicator_no": "3.1.31", "description": "Infected"},
            {"indicator_no": "3.1.32", "description": "International health policy"},
            {"indicator_no": "3.1.33", "description": "International health regulations"},
            {"indicator_no": "3.1.34", "description": "Malaria"},
            {"indicator_no": "3.1.35", "description": "Maternal mortality"},
            {"indicator_no": "3.1.36", "description": "Measles"},
            {"indicator_no": "3.1.37", "description": "Medical"},
            {"indicator_no": "3.1.38", "description": "Mental health"},
            {"indicator_no": "3.1.39", "description": "Mortality"},
            {"indicator_no": "3.1.40", "description": "Mortality rate"},
            {"indicator_no": "3.1.41", "description": "Narcotic drug abuse"},
            {"indicator_no": "3.1.42", "description": "Neonatal mortality"},
            {"indicator_no": "3.1.43", "description": "Polio"},
            {"indicator_no": "3.1.44", "description": "Premature mortality"},
            {"indicator_no": "3.1.45", "description": "Preventable deaths"},
            {"indicator_no": "3.1.46", "description": "Reducing malaria"},
            {"indicator_no": "3.1.47", "description": "Reducing mortality"},
            {"indicator_no": "3.1.48", "description": "Refugees and health services"},
            {"indicator_no": "3.1.49", "description": "Reproductive health"},
            {"indicator_no": "3.1.50", "description": "Road traffic accidents"},
            {"indicator_no": "3.1.51", "description": "Sexual and reproductive health-care"},
            {"indicator_no": "3.1.52", "description": "Sexual health"},
            {"indicator_no": "3.1.53", "description": "Soil contamination"},
            {"indicator_no": "3.1.54", "description": "Soil pollution"},
            {"indicator_no": "3.1.55", "description": "Tobacco control"},
            {"indicator_no": "3.1.56", "description": "Treatment of substance abuse"},
            {"indicator_no": "3.1.57", "description": "Tuberculosis"},
            {"indicator_no": "3.1.58", "description": "Universal health access"},
            {"indicator_no": "3.1.59", "description": "Universal health coverage"},
            {"indicator_no": "3.1.60", "description": "Vaccines"},
            {"indicator_no": "3.1.61", "description": "Vaccines in developing countries"},
            {"indicator_no": "3.1.62", "description": "Violence"},
            {"indicator_no": "3.1.63", "description": "Water, Sanitation and Hygiene for All"},
            {"indicator_no": "3.1.64", "description": "Water-borne disease"},
            {"indicator_no": "3.1.65", "description": "Well-being"},
            {"indicator_no": "3.1.66", "description": "World Health Organisation"}
        ]
    },
    {
        "sdg_no": 4,
        "title": "Quality Education",
        "content": "Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all.",
        "targets": [],
        "indicators": [
            {"indicator_no": "4.1.1", "description": "Access to education"},
            {"indicator_no": "4.1.2", "description": "Basic education"},
            {"indicator_no": "4.1.3", "description": "Basic literacy"},
            {"indicator_no": "4.1.4", "description": "Basic literacy skills"},
            {"indicator_no": "4.1.5", "description": "Cultural diversity"},
            {"indicator_no": "4.1.6", "description": "Disability"},
            {"indicator_no": "4.1.7", "description": "Disability and education"},
            {"indicator_no": "4.1.8", "description": "Early childhood"},
            {"indicator_no": "4.1.9", "description": "Early childhood development"},
            {"indicator_no": "4.1.10", "description": "Education"},
            {"indicator_no": "4.1.11", "description": "Education for sustainability"},
            {"indicator_no": "4.1.12", "description": "Education in developing"},
            {"indicator_no": "4.1.13", "description": "Enrolment"},
            {"indicator_no": "4.1.14", "description": "Equal access"},
            {"indicator_no": "4.1.15", "description": "Equal education"},
            {"indicator_no": "4.1.16", "description": "Equitable education"},
            {"indicator_no": "4.1.17", "description": "Gender disparities in education"},
            {"indicator_no": "4.1.18", "description": "Gender disparity"},
            {"indicator_no": "4.1.19", "description": "Gender equality"},
            {"indicator_no": "4.1.20", "description": "Gender equity"},
            {"indicator_no": "4.1.21", "description": "Gender sensitive"},
            {"indicator_no": "4.1.22", "description": "Global citizenship"},
            {"indicator_no": "4.1.23", "description": "Global education"},
            {"indicator_no": "4.1.24", "description": "Inclusion and education"},
            {"indicator_no": "4.1.25", "description": "Inclusive"},
            {"indicator_no": "4.1.26", "description": "Innovation"},
            {"indicator_no": "4.1.27", "description": "International cooperation"},
            {"indicator_no": "4.1.28", "description": "Learning opportunities"},
            {"indicator_no": "4.1.29", "description": "Lifelong learning"},
            {"indicator_no": "4.1.30", "description": "Literacy"},
            {"indicator_no": "4.1.31", "description": "Literacy skills"},
            {"indicator_no": "4.1.32", "description": "Numeracy"},
            {"indicator_no": "4.1.33", "description": "Preprimary education"},
            {"indicator_no": "4.1.34", "description": "Primary education"},
            {"indicator_no": "4.1.35", "description": "Qualified teachers"},
            {"indicator_no": "4.1.36", "description": "Refugees and learning"},
            {"indicator_no": "4.1.37", "description": "Scholarships"},
            {"indicator_no": "4.1.38", "description": "School"},
            {"indicator_no": "4.1.39", "description": "School enrolment"},
            {"indicator_no": "4.1.40", "description": "Secondary education"},
            {"indicator_no": "4.1.41", "description": "Teacher training"},
            {"indicator_no": "4.1.42", "description": "Universal education"},
            {"indicator_no": "4.1.43", "description": "Vocational training"},
            {"indicator_no": "4.1.44", "description": "Vulnerable"},
            {"indicator_no": "4.1.45", "description": "Women's rights"}
        ]
    },
    {
        "sdg_no": 5,
        "title": "Gender Equality",
        "content": "Achieve gender equality and empower all women and girls.",
        "targets": [],
        "indicators": [
            {"indicator_no": "5.1.1", "description": "Basic living standards"},
            {"indicator_no": "5.1.2", "description": "Dignity"},
            {"indicator_no": "5.1.3", "description": "Disadvantaged"},
            {"indicator_no": "5.ruits"},
            {"indicator_no": "5.1.5", "description": "Employment"},
            {"indicator_no": "5.1.6", "description": "Empower girls"},
            {"indicator_no": "5.1.7", "description": "Empowerment"},
            {"indicator_no": "5.1.8", "description": "Empowerment of women"},
            {"indicator_no": "5.1.9", "description": "Equal access"},
            {"indicator_no": "5.1.10", "description": "Equal opportunities"},
            {"indicator_no": "5.1.11", "description": "Equality"},
            {"indicator_no": "5.1.12", "description": "Exploitation"},
            {"indicator_no": "5.1.13", "description": "Female genital mutilation"},
            {"indicator_no": "5.1.14", "description": "Feminism"},
            {"indicator_no": "5.1.15", "description": "Forced marriage"},
            {"indicator_no": "5.1.16", "description": "Gender"},
            {"indicator_no": "5.1.17", "description": "Gender discrimination"},
            {"indicator_no": "5.1.18", "description": "Parity"},
            {"indicator_no": "5.1.19", "description": "Gender equality"},
            {"indicator_no": "5.1.20", "description": "Governance and gender"},
            {"indicator_no": "5.1.21", "description": "Human rights"},
            {"indicator_no": "5.1.22", "description": "Human trafficking"},
            {"indicator_no": "5.1.23", "description": "Humanitarian"},
            {"indicator_no": "5.1.24", "description": "Marginalised"},
            {"indicator_no": "5.1.25", "description": "Pay"},
            {"indicator_no": "5.1.26", "description": "Reproductive rights"},
            {"indicator_no": "5.1.27", "description": "Sexual and reproductive health"},
            {"indicator_no": "5.1.28", "description": "Sexual exploitation"},
            {"indicator_no": "5.1.29", "description": "Sexual violence"},
            {"indicator_no": "5.1.30", "description": "Social inclusion"},
            {"indicator_no": "5.1.31", "description": "Trafficking"},
            {"indicator_no": "5.1.32", "description": "Universal health coverage"},
            {"indicator_no": "5.1.33", "description": "Violence"},
            {"indicator_no": "5.1.34", "description": "Violence against girls"},
            {"indicator_no": "5.1.35", "description": "Violence against women"},
            {"indicator_no": "5.1.36", "description": "Women"},
            {"indicator_no": "5.1.37", "description": "Women in work"},
            {"indicator_no": "5.1.38", "description": "Women's rights"},
            {"indicator_no": "5.1.39", "description": "Workplace equality"},
            {"indicator_no": "5.1.40", "description": "Empower women"},
            {"indicator_no": "5.1.41", "description": "Women's empowerment"}
        ]
    },
    {
        "sdg_no": 6,
        "title": "Clean Water and Sanitation",
        "content": "Ensure availability and sustainable management of water and sanitation for all.",
        "targets": [
            {"target_no": "6.1", "description": "By 2030, achieve universal and equitable access to safe and affordable drinking water for all."}
        ],
        "indicators": [
            {"indicator_no": "6.1.1", "description": "Accessible water"},
            {"indicator_no": "6.1.2", "description": "Affordable drinking water"},
            {"indicator_no": "6.1.3", "description": "Aquifer"},
            {"indicator_no": "6.1.4", "description": "Cities"},
            {"indicator_no": "6.1.5", "description": "Clean water"},
            {"indicator_no": "6.1.6", "description": "Contaminated"},
            {"indicator_no": "6.1.7", "description": "Defecation"},
            {"indicator_no": "6.1.8", "description": "Desalination"},
            {"indicator_no": "6.1.9", "description": "Diarrhoeal diseases"},
            {"indicator_no": "6.1.10", "description": "Drought"},
            {"indicator_no": "6.1.11", "description": "Dumping"},
            {"indicator_no": "6.1.12", "description": "Ecosystem protection"},
            {"indicator_no": "6.1.13", "description": "Ecosystem restoration"},
            {"indicator_no": "6.1.14", "description": "Equitable sanitation"},
            {"indicator_no": "6.1.15", "description": "Floods"},
            {"indicator_no": "6.1.16", "description": "Fresh water"},
            {"indicator_no": "6.1.17", "description": "Hydropower"},
            {"indicator_no": "6.1.18", "description": "Hygiene"},
            {"indicator_no": "6.1.19", "description": "Improving water"},
            {"indicator_no": "6.1.20", "description": "Inadequate water"},
            {"indicator_no": "6.1.21", "description": "Inadequate water supply"},
            {"indicator_no": "6.1.22", "description": "Infrastructure"},
            {"indicator_no": "6.1.23", "description": "Irrigation"},
            {"indicator_no": "6.1.24", "description": "Lakes"},
            {"indicator_no": "6.1.25", "description": "Latrines"},
            {"indicator_no": "6.1.26", "description": "Open defecation"},
            {"indicator_no": "6.1.27", "description": "Pollution"},
            {"indicator_no": "6.1.28", "description": "Recycled water"},
            {"indicator_no": "6.1.29", "description": "Reuse"},
            {"indicator_no": "6.1.30", "description": "River basins"},
            {"indicator_no": "6.1.31", "description": "Rivers"},
            {"indicator_no": "6.1.32", "description": "Safe drinking water"},
            {"indicator_no": "6.1.33", "description": "Sanitation"},
            {"indicator_no": "6.1.34", "description": "Sanitation and hygiene"},
            {"indicator_no": "6.1.35", "description": "Sanitation management"},
            {"indicator_no": "6.1.36", "description": "Sewerage"},
            {"indicator_no": "6.1.37", "description": "Sustainable water management"},
            {"indicator_no": "6.1.38", "description": "Sustainable withdrawals"},
            {"indicator_no": "6.1.39", "description": "Third world"},
            {"indicator_no": "6.1.40", "description": "Toilets"},
            {"indicator_no": "6.1.41", "description": "Untreated wastewater"},
            {"indicator_no": "6.1.42", "description": "Urban"},
            {"indicator_no": "6.1.43", "description": "Waste"},
            {"indicator_no": "6.1.44", "description": "Wastewater"},
            {"indicator_no": "6.1.45", "description": "Wastewater treatment"},
            {"indicator_no": "6.1.46", "description": "Water"},
            {"indicator_no": "6.1.47", "description": "Water access"},
            {"indicator_no": "6.1.48", "description": "Water disasters"},
            {"indicator_no": "6.1.49", "description": "Water ecosystems"},
            {"indicator_no": "6.1.50", "description": "Water efficiency"},
            {"indicator_no": "6. Ascertain"},
            {"indicator_no": "6.1.51", "description": "Water harvesting"},
            {"indicator_no": "6.1.52", "description": "Water quality"},
            {"indicator_no": "6.1.53", "description": "Water resources management"},
            {"indicator_no": "6.1.54", "description": "Water scarcity"},
            {"indicator_no": "6.1.55", "description": "Water supply"},
            {"indicator_no": "6.1.56", "description": "Water-related ecosystems"},
            {"indicator_no": "6.1.57", "description": "Water-use efficiency"}
        ]
    },
    {
        "sdg_no": 7,
        "title": "Affordable and Clean Energy",
        "content": "Ensure access to affordable, reliable, sustainable and modern energy for all.",
        "targets": [
            {"target_no": "7.1", "description": "By 2030, ensure universal access to affordable, reliable and modern energy services."}
        ],
        "indicators": [
            {"indicator_no": "7.1.1", "description": "Affordable energy"},
            {"indicator_no": "7.1.2", "description": "Alternative energy"},
            {"indicator_no": "7.1.3", "description": "Animal waste"},
            {"indicator_no": "7.1.4", "description": "Battery"},
            {"indicator_no": "7.1.5", "description": "Carbon"},
            {"indicator_no": "7.1.6", "description": "Charcoal"},
            {"indicator_no": "7.1.7", "description": "Clean energy"},
            {"indicator_no": "7.1.8", "description": "Clean energy technology"},
            {"indicator_no": "7.1.9", "description": "Clean fuel technology"},
            {"indicator_no": "7.1.10", "description": "Clean fuels"},
            {"indicator_no": "7.1.11", "description": "Cleaner fossil fuel technology"},
            {"indicator_no": "7.1.12", "description": "Climate goal"},
            {"indicator_no": "7.1.13", "description": "Coal"},
            {"indicator_no": "7.1.14", "description": "Electricity"},
            {"indicator_no": "7.1.15", "description": "Electricity infrastructure"},
            {"indicator_no": "7.1.16", "description": "Emissions"},
            {"indicator_no": "7.1.17", "description": "Energy"},
            {"indicator_no": "7.1.18", "description": "Energy efficiency"},
            {"indicator_no": "7.1.19", "description": "Energy infrastructure"},
            {"indicator_no": "7.1.20", "description": "Energy research"},
            {"indicator_no": "7.1.21", "description": "Energy technology"},
            {"indicator_no": "7.1.22", "description": "Fossil-fuel"},
            {"indicator_no": "7.1.23", "description": "Green economy"},
            {"indicator_no": "7.1.24", "description": "Greenhouse gas"},
            {"indicator_no": "7.1.25", "description": "Greenhouse gas emissions"},
            {"indicator_no": "7.1.26", "description": "Hydroelectric"},
            {"indicator_no": "7.1.27", "description": "Low carbon"},
            {"indicator_no": "7.1.28", "description": "Modern electricity"},
            {"indicator_no": "7.1.29", "description": "Modern energy"},
            {"indicator_no": "7.1.30", "description": "Reliable energy"},
            {"indicator_no": "7.1.31", "description": "Renewable"},
            {"indicator_no": "7.1.32", "description": "Renewable energy"},
            {"indicator_no": "7.1.33", "description": "Renewable power"},
            {"indicator_no": "7.1.34", "description": "Solar"},
            {"indicator_no": "7.1.35", "description": "Solar energy"},
            {"indicator_no": "7.1.36", "description": "Solar power"},
            {"indicator_no": "7.1.37", "description": "Sustainable energy"},
            {"indicator_no": "7.1.38", "description": "Sustainable energy services"},
            {"indicator_no": "7.1.39", "description": "Sustainable power"},
            {"indicator_no": "7.1.40", "description": "Vehicles"},
            {"indicator_no": "7.1.41", "description": "Wave"},
            {"indicator_no": "7.1.42", "description": "Wind"},
            {"indicator_no": "7.1.43", "description": "Wind power"},
            {"indicator_no": "7.1.44", "description": "Wind turbine"},
            {"indicator_no": "7.1.45", "description": "Wood"}
        ]
    },
    {
        "sdg_no": 8,
        "title": "Decent Work and Economic Growth",
        "content": "Promote sustained, inclusive and sustainable economic growth, full and productive employment and decent work for all.",
        "targets": [
            {"target_no": "8.1", "description": "Sustain per capita economic growth in accordance with national circumstances and, in particular, at least 7 per cent gross domestic product growth per annum in the least developed countries."}
        ],
        "indicators": [
            {"indicator_no": "8.1.1", "description": "Labour rights"},
            {"indicator_no": "8.1.2", "description": "Micro finance"},
            {"indicator_no": "8.1.3", "description": "Migrant workers"},
            {"indicator_no": "8.1.4", "description": "Modern slavery"},
            {"indicator_no": "8.1.5", "description": "Poverty eradication"},
            {"indicator_no": "8.1.6", "description": "Poverty line"},
            {"indicator_no": "8.1.7", "description": "Productive employment"},
            {"indicator_no": "8.1.8", "description": "Productivity"},
            {"indicator_no": "8.1.9", "description": "Public policy"},
            {"indicator_no": "8.1.10", "description": "Quality jobs"},
            {"indicator_no": "8.1.11", "description": "Quality of life"},
            {"indicator_no": "8.1.12", "description": "Resource efficiency"},
            {"indicator_no": "8.1.13", "description": "Safe work"},
            {"indicator_no": "8.1.14", "description": "Secure work"},
            {"indicator_no": "8.1.15", "description": "Slavery"},
            {"indicator_no": "8.1.16", "description": "Social policies"},
            {"indicator_no": "8.1.17", "description": "Society"},
            {"indicator_no": "8.1.18", "description": "Stable employment"},
            {"indicator_no": "8.1.19", "description": "Stable jobs"},
            {"indicator_no": "8.1.20", "description": "Sustainable consumption"},
            {"indicator_no": "8.1.21", "description": "Sustainable economic growth"},
            {"indicator_no": "8.1.22", "description": "Sustainable production"},
            {"indicator_no": "8.1.23", "description": "Sustainable tourism"},
            {"indicator_no": "8.1.24", "description": "Trade"},
            {"indicator_no": "8.1.25", "description": "Unemployment"},
            {"indicator_no": "8.1.26", "description": "Well-paid jobs"},
            {"indicator_no": "8.1.27", "description": "Women migrants"},
            {"indicator_no": "8.1.28", "description": "Work"},
            {"indicator_no": "8.1.29", "description": "Work opportunities"},
            {"indicator_no": "8.1.30", "description": "World trade"},
            {"indicator_no": "8.1.31", "description": "Youth employment"},
            {"indicator_no": "8.1.32", "description": "Youth unemployment"}
        ]
    },
    {
        "sdg_no": 9,
        "title": "Industry, Innovation and Infrastructure",
        "content": "Build resilient infrastructure, promote inclusive and sustainable industrialization and foster innovation.",
        "targets": [
            {"target_no": "9.1", "description": "Develop quality, reliable, sustainable and resilient infrastructure, including regional and transborder infrastructure, to support economic development and human well-being, with a focus on affordable and equitable access for all."}
        ],
        "indicators": [
            {"indicator_no": "9.1.1", "description": "Research"},
            {"indicator_no": "9.1.2", "description": "Resilient infrastructure"},
            {"indicator_no": "9.1.3", "description": "Resource use efficiency"},
            {"indicator_no": "9.1.4", "description": "Roads"},
            {"indicator_no": "9.1.5", "description": "Sanitation"},
            {"indicator_no": "9.1.6", "description": "Scientific research"},
            {"indicator_no": "9.1.7", "description": "Society"},
            {"indicator_no": "9.1.8", "description": "Sustainable industrialisation"},
            {"indicator_no": "9.1.9", "description": "Sustainable infrastructure"},
            {"indicator_no": "9.1.10", "description": "Technological capabilities"},
            {"indicator_no": "9.1.11", "description": "Technology"},
            {"indicator_no": "9.1.12", "description": "Trade"},
            {"indicator_no": "9.1.13", "description": "Transborder infrastructure"},
            {"indicator_no": "9.1.14", "description": "Transport"},
            {"indicator_no": "9.1.15", "description": "Value chains"},
            {"indicator_no": "9.1.16", "description": "Value chains and markets"},
            {"indicator_no": "9.1.17", "description": "Water infrastructure"},
            {"indicator_no": "9.1.18", "description": "Water resources"}
        ]
    },
    {
        "sdg_no": 10,
        "title": "Reduced Inequalities",
        "content": "Reduce income inequality within and among countries.",
        "targets": [
            {"target_no": "10.1", "description": "By 2030, progressively achieve and sustain income growth of the bottom 40 per cent of the population at a rate higher than the national average."}
        ],
        "indicators": [
            {"indicator_no": "10.1.1", "description": "Human rights"},
            {"indicator_no": "10.1.2", "description": "Inclusion"},
            {"indicator_no": "10.1.3", "description": "Income growth"},
            {"indicator_no": "10.1.4", "description": "Income inequality"},
            {"indicator_no": "10.1.5", "description": "Indigenous"},
            {"indicator_no": "10.1.6", "description": "Inequalities"},
            {"indicator_no": "10.1.7", "description": "Inequality"},
            {"indicator_no": "10.1.8", "description": "Migrant remittance"},
            {"indicator_no": "10.1.9", "description": "Migration"},
            {"indicator_no": "10.1.10", "description": "Population growth"},
            {"indicator_no": "10.1.11", "description": "Poverty"},
            {"indicator_no": "10.1.12", "description": "Public policy"},
            {"indicator_no": "10.1.13", "description": "Quality of life"},
            {"indicator_no": "10.1.14", "description": "Race"},
            {"indicator_no": "10.1.15", "description": "Racism"},
            {"indicator_no": "10.1.16", "description": "Reduce inequalities"},
            {"indicator_no": "10.1.17", "description": "Religion"},
            {"indicator_no": "10.1.18", "description": "Rural"},
            {"indicator_no": "10.1.19", "description": "Sex"},
            {"indicator_no": "10.1.20", "description": "Sexism"},
            {"indicator_no": "10.1.21", "description": "Social protection"},
            {"indicator_no": "10.1.22", "description": "Society"},
            {"indicator_no": "10.1.23", "description": "Vulnerable nations"},
            {"indicator_no": "10.1.24", "description": "World trade"}
        ]
    },
    {
        "sdg_no": 11,
        "title": "Sustainable Cities and Communities",
        "content": "Make cities and human settlements inclusive, safe, resilient and sustainable.",
        "targets": [
            {"target_no": "11.1", "description": "By 2030, ensure access for all to adequate, safe and affordable housing and basic services and upgrade slums."}
        ],
        "indicators": [
            {"indicator_no": "11.1.1", "description": "Public transport"},
            {"indicator_no": "11.1.2", "description": "Resilient"},
            {"indicator_no": "11.1.3", "description": "Resilient buildings"},
            {"indicator_no": "11.1.4", "description": "Resource efficiency"},
            {"indicator_no": "11.1.5", "description": "Resource needs"},
            {"indicator_no": "11.1.6", "description": "Risk reduction strategy"},
            {"indicator_no": "11.1.7", "description": "Road safety"},
            {"indicator_no": "11.1.8", "description": "Safe cities"},
            {"indicator_no": "11.1.9", "description": "Shanty"},
            {"indicator_no": "11.1.10", "description": "Slums"},
            {"indicator_no": "11.1.11", "description": "Smart cities"},
            {"indicator_no": "11.1.12", "description": "Solid waste"},
            {"indicator_no": "11.1.13", "description": "Suburban"},
            {"indicator_no": "11.1.14", "description": "Sustainable"},
            {"indicator_no": "11.1.15", "description": "Sustainable building"},
            {"indicator_no": "11.1.16", "description": "Sustainable buildings"},
            {"indicator_no": "11.1.17", "description": "Sustainable city"},
            {"indicator_no": "11.1.18", "description": "Sustainable cities"},
            {"indicator_no": "11.1.19", "description": "Sustainable communities"},
            {"indicator_no": "11.1.20", "description": "Sustainable urbanisation"},
            {"indicator_no": "11.1.21", "description": "Town planning"},
            {"indicator_no": "11.1.22", "description": "Transport"},
            {"indicator_no": "11.1.23", "description": "Transport systems"},
            {"indicator_no": "11.1.24", "description": "Urban"},
            {"indicator_no": "11.1.25", "description": "Urban development"},
            {"indicator_no": "11.1.26", "description": "Urban planning"},
            {"indicator_no": "11.1.27", "description": "Urban sustainability"},
            {"indicator_no": "11.1.28", "description": "Urbanisation"},
            {"indicator_no": "11.1.29", "description": "Waste"},
            {"indicator_no": "11.1.30", "description": "Waste generation"},
            {"indicator_no": "11.1.31", "description": "Waste management"},
            {"indicator_no": "11.1.32", "description": "Water"},
            {"indicator_no": "11.1.33", "description": "Water-related disasters"}
        ]
    },
    {
        "sdg_no": 12,
        "title": "Responsible Consumption and Production",
        "content": "Ensure sustainable consumption and production patterns.",
        "targets": [
            {"target_no": "12.1", "description": "Implement the 10-year framework of programmes on sustainable consumption and production, all countries taking action, with developed countries taking the lead, taking into account the development and capabilities of developing countries."}
        ],
        "indicators": [
            {"indicator_no": "12.1.1", "description": "Capitalism"},
            {"indicator_no": "12.1.2", "description": "Cars"},
            {"indicator_no": "12.1.3", "description": "Circular economy"},
            {"indicator_no": "12.1.4", "description": "Commercial enterprises"},
            {"indicator_no": "12.1.5", "description": "Consumer levels"},
            {"indicator_no": "12.1.6", "description": "Consumerism"},
            {"indicator_no": "12.1.7", "description": "Consumption"},
            {"indicator_no": "12.1.8", "description": "Deep decarbonisation"},
            {"indicator_no": "12.1.9", "description": "Ecological"},
            {"indicator_no": "12.1.10", "description": "Efficient use of resources"},
            {"indicator_no": "12.1.11", "description": "Energy"},
            {"indicator_no": "12.1.12", "description": "Energy consumption"},
            {"indicator_no": "12.1.13", "description": "Energy efficiency"},
            {"indicator_no": "12.1.14", "description": "Energy use"},
            {"indicator_no": "12.1.15", "description": "Food"},
            {"indicator_no": "12.1.16", "description": "Food losses"},
            {"indicator_no": "12.1.17", "description": "Food supply"},
            {"indicator_no": "12.1.18", "description": "Food waste"},
            {"indicator_no": "12.1.19", "description": "Fossil fuel subsidies"},
            {"indicator_no": "12.1.20", "description": "Future proof"},
            {"indicator_no": "12.1.21", "description": "Global food waste"},
            {"indicator_no": "12.1.22", "description": "Greenhouse gasses"},
            {"indicator_no": "12.1.23", "description": "Harvest losses"},
            {"indicator_no": "12.1.24", "description": "Life cycle"},
            {"indicator_no": "12.1.25", "description": "Market distortions"},
            {"indicator_no": "12.1.26", "description": "Materialism"},
            {"indicator_no": "12.1.27", "description": "Materials goods"},
            {"indicator_no": "12.1.28", "description": "Monitoring sustainable development"},
            {"indicator_no": "12.1.29", "description": "Natural resources"},
            {"indicator_no": "12.1.30", "description": "Obsolescence"},
            {"indicator_no": "12.1.31", "description": "Overconsumption"},
            {"indicator_no": "12.1.32", "description": "Production"},
            {"indicator_no": "12.1.33", "description": "Recycle"},
            {"indicator_no": "12.1.34", "description": "Recycling"},
            {"indicator_no": "12.1.35", "description": "Reduce waste generation"},
            {"indicator_no": "12.1.36", "description": "Reduction"},
            {"indicator_no": "12.1.37", "description": "Renewable"},
            {"indicator_no": "12.1.38", "description": "Resource efficiency"},
            {"indicator_no": "12.1.39", "description": "Responsible production chains"},
            {"indicator_no": "12.1.40", "description": "Retail"},
            {"indicator_no": "12.1.41", "description": "Retail industry"},
            {"indicator_no": "12.1.42", "description": "Reuse"},
            {"indicator_no": "12.1.43", "description": "Sustainable"},
            {"indicator_no": "12.1.44", "description": "Sustainable consumption"},
            {"indicator_no": "12.1.45", "description": "Sustainable management"},
            {"indicator_no": "12.1.46", "description": "Sustainable practices"},
            {"indicator_no": "12.1.47", "description": "Sustainable production"},
            {"indicator_no": "12.1.48", "description": "Sustainable public procurement"},
            {"indicator_no": "12.1.49", "description": "Sustainable resource use"},
            {"indicator_no": "12.1.50", "description": "Sustainable supply chain"},
            {"indicator_no": "12.1.51", "description": "Sustainable tourism"},
            {"indicator_no": "12.1.52", "description": "Vehicles"},
            {"indicator_no": "12.1.53", "description": "Waste"},
            {"indicator_no": "12.1.54", "description": "Wasteful consumption"},
            {"indicator_no": "12.1.55", "description": "Water"},
            {"indicator_no": "12.1.56", "description": "Water pollution"},
            {"indicator_no": "12.1.57", "description": "Water supply"}
        ]
    },
    {
        "sdg_no": 13,
        "title": "Climate Action",
        "content": "Take urgent action to combat climate change and its impacts.",
        "targets": [
            {"target_no": "13.1", "description": "Strengthen resilience and adaptive capacity to climate-related hazards and natural disasters in all countries."}
        ],
        "indicators": [
            {"indicator_no": "13.1.1", "description": "Average global temperature"},
            {"indicator_no": "13.1.2", "description": "Carbon"},
            {"indicator_no": "13.1.3", "description": "Carbon dioxide"},
            {"indicator_no": "13.1.4", "description": "Changing weather patterns"},
            {"indicator_no": "13.1.5", "description": "Climate"},
            {"indicator_no": "13.1.6", "description": "Climate action"},
            {"indicator_no": "13.1.7", "description": "Climate adaptation"},
            {"indicator_no": "13.1.8", "description": "Climate and gender"},
            {"indicator_no": "13.1.9", "description": "Climate and infectious disease"},
            {"indicator_no": "13.1.10", "description": "Climate and politics"},
            {"indicator_no": "13.1.11", "description": "Climate change"},
            {"indicator_no": "13.1.12", "description": "Climate change management"},
            {"indicator_no": "13.1.13", "description": "Climate change planning"},
            {"indicator_no": "13.1.14", "description": "Climate change policy"},
            {"indicator_no": "13.1.15", "description": "Climate early warning"},
            {"indicator_no": "13.1.16", "description": "Climate hazards"},
            {"indicator_no": "13.1.17", "description": "Climate impact"},
            {"indicator_no": "13.1.18", "description": "Climate mitigation"},
            {"indicator_no": "13.1.19", "description": "Climate refugees"},
            {"indicator_no": "13.1.20", "description": "Climate related hazards"},
            {"indicator_no": "13.1.21", "description": "Climate resilience"},
            {"indicator_no": "13.1.22", "description": "CO2 capture"},
            {"indicator_no": "13.1.23", "description": "CO2 conversion"},
            {"indicator_no": "13.1.24", "description": "COP 21"},
            {"indicator_no": "13.1.25", "description": "COP 22"},
            {"indicator_no": "13.1.26", "description": "Ecosystems"},
            {"indicator_no": "13.1.27", "description": "Emissions"},
            {"indicator_no": "13.1.28", "description": "Extreme weather"},
            {"indicator_no": "13.1.29", "description": "Extreme weather events"},
            {"indicator_no": "13.1.30", "description": "Global mean temperature"},
            {"indicator_no": "13.1.31", "description": "Global temperature"},
            {"indicator_no": "13.1.32", "description": "Global warming"},
            {"indicator_no": "13.1.33", "description": "Greenhouse gas"},
            {"indicator_no": "13.1.34", "description": "Greenhouse gas emissions"},
            {"indicator_no": "13.1.35", "description": "Greenhouse gases"},
            {"indicator_no": "13.1.36", "description": "Ice loss"},
            {"indicator_no": "13.1.37", "description": "Low-carbon economy"},
            {"indicator_no": "13.1.38", "description": "Natural disasters"},
            {"indicator_no": "13.1.39", "description": "Natural systems"},
            {"indicator_no": "13.1.40", "description": "Ocean warming"},
            {"indicator_no": "13.1.41", "description": "Paris Agreement"},
            {"indicator_no": "13.1.42", "description": "Pollution"},
            {"indicator_no": "13.1.43", "description": "Renewable"},
            {"indicator_no": "13.1.44", "description": "Rising sea"},
            {"indicator_no": "13.1.45", "description": "Rising sea level"},
            {"indicator_no": "13.1.46", "description": "Sea level rise"},
            {"indicator_no": "13.1.47", "description": "Temperature"},
            {"indicator_no": "13.1.48", "description": "Warming"}
        ]
    },
    {
        "sdg_no": 14,
        "title": "Life Below Water",
        "content": "Conserve and sustainably use the oceans, seas and marine resources for sustainable development.",
        "targets": [
            {"target_no": "14.1", "description": "By 2025, prevent and significantly reduce marine pollution of all kinds, in particular from land-based activities, including nutrient pollution and marine debris."}
        ],
        "indicators": [
            {"indicator_no": "14.1.1", "description": "Artisanal fishers"},
            {"indicator_no": "14.1.2", "description": "Biodiversity"},
            {"indicator_no": "14.1.3", "description": "Carbon dioxide"},
            {"indicator_no": "14.1.4", "description": "Coastal biodiversity"},
            {"indicator_no": "14.1.5", "description": "Coastal ecosystems"},
            {"indicator_no": "14.1.6", "description": "Coastal habitats"},
            {"indicator_no": "14.1.7", "description": "Coastal parks"},
            {"indicator_no": "14.1.8", "description": "Coastal resources"},
            {"indicator_no": "14.1.9", "description": "Coastlines"},
            {"indicator_no": "14.1.10", "description": "Conserve"},
            {"indicator_no": "14.1.11", "description": "Conserve oceans"},
            {"indicator_no": "14.1.12", "description": "Coral bleaching"},
            {"indicator_no": "14.1.13", "description": "Coral reef"},
            {"indicator_no": "14.1.14", "description": "Ecosystem management"},
            {"indicator_no": "14.1.15", "description": "Fish species"},
            {"indicator_no": "14.1.16", "description": "Fish stocks"},
            {"indicator_no": "14.1.17", "description": "Fish stocks AND FISHERIES MANAGEMENT"},
            {"indicator_no": "14.1.18", "description": "Fisheries"},
            {"indicator_no": "14.1.19", "description": "Fishers"},
            {"indicator_no": "14.1.20", "description": "Fishing"},
            {"indicator_no": "14.1.21", "description": "Fishing practices"},
            {"indicator_no": "14.1.22", "description": "Global warming"},
            {"indicator_no": "14.1.23", "description": "Illegal fishing"},
            {"indicator_no": "14.1.24", "description": "Kelp"},
            {"indicator_no": "14.1.25", "description": "Law of the Sea"},
            {"indicator_no": "14.1.26", "description": "Marine"},
            {"indicator_no": "14.1.27", "description": "Marine areas"},
            {"indicator_no": "14.1.28", "description": "Marine biodiversity"},
            {"indicator_no": "14.1.29", "description": "Marine ecosystems"},
            {"indicator_no": "14.1.30", "description": "Marine fisheries"},
            {"indicator_no": "14.1.31", "description": "Marine Parks"},
            {"indicator_no": "14.1.32", "description": "Marine pollution"},
            {"indicator_no": "14.1.33", "description": "Marine resources"},
            {"indicator_no": "14.1.34", "description": "Ocean"},
            {"indicator_no": "14.1.35", "description": "Ocean acidification"},
            {"indicator_no": "14.1.36", "description": "Ocean temperature"},
            {"indicator_no": "14.1.37", "description": "Oceanography"},
            {"indicator_no": "14.1.38", "description": "Oceans"},
            {"indicator_no": "14.1.39", "description": "Overfishing"},
            {"indicator_no": "14.1.40", "description": "Productive oceans"},
            {"indicator_no": "14.1.41", "description": "Protected areas"},
            {"indicator_no": "14.1.42", "description": "Sea grasses"},
            {"indicator_no": "14.1.43", "description": "Seas"},
            {"indicator_no": "14.1.44", "description": "Sustainable ecosystems"},
            {"indicator_no": "14.1.45", "description": "Unregulated fishing"},
            {"indicator_no": "14.1.46", "description": "Water resources and policy"}
        ]
    },
    {
        "sdg_no": 15,
        "title": "Life on Land",
        "content": "Protect, restore and promote sustainable use of terrestrial ecosystems, sustainably manage forests, combat desertification, halt and reverse land degradation and halt biodiversity loss.",
        "targets": [
            {"target_no": "15.1", "description": "By 2020, ensure the conservation, restoration and sustainable use of terrestrial and inland freshwater ecosystems and their services, in particular forests, wetlands, mountains and drylands, in line with obligations under international agreements."}
        ],
        "indicators": [
            {"indicator_no": "15.1.1", "description": "Afforestation"},
            {"indicator_no": "15.1.2", "description": "Agriculture"},
            {"indicator_no": "15.1.3", "description": "Animals"},
            {"indicator_no": "15.1.4", "description": "Arable land"},
            {"indicator_no": "15.1.5", "description": "Bees"},
            {"indicator_no": "15.1.6", "description": "Biodiversity"},
            {"indicator_no": "15.1.7", "description": "Biodiversity loss"},
            {"indicator_no": "15.1.8", "description": "Conservation"},
            {"indicator_no": "15.1.9", "description": "Deforestation"},
            {"indicator_no": "15.1.10", "description": "Desertification"},
            {"indicator_no": "15.1.11", "description": "Drought"},
            {"indicator_no": "15.1.12", "description": "Drylands"},
            {"indicator_no": "15.1.13", "description": "Ecosystem"},
            {"indicator_no": "15.1.14", "description": "Ecosystem restoration"},
            {"indicator_no": "15.1.15", "description": "Ecosystems"},
            {"indicator_no": "15.1.16", "description": "Extinct"},
            {"indicator_no": "15.1.17", "description": "Extinct species"},
            {"indicator_no": "15.1.18", "description": "Extinction"},
            {"indicator_no": "15.1.19", "description": "Forest"},
            {"indicator_no": "15.1.20", "description": "Forest management"},
            {"indicator_no": "15.1.21", "description": "Forests"},
            {"indicator_no": "15.1.22", "description": "Genetic resources"},
            {"indicator_no": "15.1.23", "description": "Illegal wildlife products"},
            {"indicator_no": "15.1.24", "description": "Illicit trafficking"},
            {"indicator_no": "15.1.25", "description": "Indigenous"},
            {"indicator_no": "15.1.26", "description": "Indigenous populations"},
            {"indicator_no": "15.1.27", "description": "Invasive alien species"},
            {"indicator_no": "15.1.28", "description": "Land conservation"},
            {"indicator_no": "15.1.29", "description": "Land degradation"},
            {"indicator_no": "15.1.30", "description": "Land loss"},
            {"indicator_no": "15.1.31", "description": "Land use and sustainability"},
            {"indicator_no": "15.1.32", "description": "Manage forests"},
            {"indicator_no": "15.1.33", "description": "Managed forests"},
            {"indicator_no": "15.1.34", "description": "Micro-organisms"},
            {"indicator_no": "15.1.35", "description": "Permaculture"},
            {"indicator_no": "15.1.36", "description": "Plants"},
            {"indicator_no": "15.1.37", "description": "Poaching"},
            {"indicator_no": "15.1.38", "description": "Poverty"},
            {"indicator_no": "15.1.39", "description": "Protected fauna"},
            {"indicator_no": "15.1.40", "description": "Protected flora"},
            {"indicator_no": "15.1.41", "description": "Protected species"},
            {"indicator_no": "15.1.42", "description": "Reforestation"},
            {"indicator_no": "15.1.43", "description": "Soil"},
            {"indicator_no": "15.1.44", "description": "Soil degradation"},
            {"indicator_no": "15.1.45", "description": "Species"},
            {"indicator_no": "15.1.46", "description": "Strategic plan for biodiversity"},
            {"indicator_no": "15.1.47", "description": "Terrestrial ecosystems"},
            {"indicator_no": "15.1.48", "description": "Threatened species"},
            {"indicator_no": "15.1.49", "description": "Tree"},
            {"indicator_no": "15.1.50", "description": "Tree species"},
            {"indicator_no": "15.1.51", "description": "Wetlands"}
        ]
    },
    {
        "sdg_no": 16,
        "title": "Peace, Justice and Strong Institutions",
        "content": "Promote peaceful and inclusive societies for sustainable development, provide access to justice for all and build effective, accountable and inclusive institutions at all levels.",
        "targets": [
            {"target_no": "16.1", "description": "Significantly reduce all forms of violence and related death rates everywhere."}
        ],
        "indicators": [
            {"indicator_no": "16.1.1", "description": "Abuse"},
            {"indicator_no": "16.1.2", "description": "Accountability"},
            {"indicator_no": "16.1.3", "description": "Accountable institutions"},
            {"indicator_no": "16.1.4", "description": "Arbitrary detention"},
            {"indicator_no": "16.1.5", "description": "Arms"},
            {"indicator_no": "16.1.6", "description": "Arms trafficking"},
            {"indicator_no": "16.1.7", "description": "Birth registration"},
            {"indicator_no": "16.1.8", "description": "Bribery"},
            {"indicator_no": "16.1.9", "description": "Combat terrorism"},
            {"indicator_no": "16.1.10", "description": "Conflict resolution"},
            {"indicator_no": "16.1.11", "description": "Conflicts"},
            {"indicator_no": "16.1.12", "description": "Corruption"},
            {"indicator_no": "16.1.13", "description": "Discrimination"},
            {"indicator_no": "16.1.14", "description": "Education"},
            {"indicator_no": "16.1.15", "description": "Enforced disappearance"},
            {"indicator_no": "16.1.16", "description": "Equal access"},
            {"indicator_no": "16.1.17", "description": "Equity"},
            {"indicator_no": "16.1.18", "description": "Exploitation"},
            {"indicator_no": "16.1.19", "description": "Flow of arms"},
            {"indicator_no": "16.1.20", "description": "Freedom"},
            {"indicator_no": "16.1.21", "description": "Geography of poverty"},
            {"indicator_no": "16.1.22", "description": "Governance"},
            {"indicator_no": "16.1.23", "description": "Hate crime"},
            {"indicator_no": "16.1.24", "description": "Human rights"},
            {"indicator_no": "16.1.25", "description": "Human trafficking"},
            {"indicator_no": "16.1.26", "description": "Illegal arms"},
            {"indicator_no": "16.1.27", "description": "Illicit financial flows"},
            {"indicator_no": "16.1.28", "description": "Inclusion"},
            {"indicator_no": "16.1.29", "description": "Inclusive institutions"},
            {"indicator_no": "16.1.30", "description": "Inclusive society"},
            {"indicator_no": "16.1.31", "description": "Institutions"},
            {"indicator_no": "16.1.32", "description": "Internally displaced"},
            {"indicator_no": "16.1.33", "description": "Judiciary"},
            {"indicator_no": "16.1.34", "description": "Justice"},
            {"indicator_no": "16.1.35", "description": "Justice for all"},
            {"indicator_no": "16.1.36", "description": "Legal identity"},
            {"indicator_no": "16.1.37", "description": "National Security"},
            {"indicator_no": "16.1.38", "description": "Non-violence"},
            {"indicator_no": "16.1.39", "description": "Organized crime"},
            {"indicator_no": "16.1.40", "description": "Paris principles"},
            {"indicator_no": "16.1.41", "description": "Peace"},
            {"indicator_no": "16.1.42", "description": "Peaceful societies"},
            {"indicator_no": "16.1.43", "description": "Physical abuse"},
            {"indicator_no": "16.1.44", "description": "Police"},
            {"indicator_no": "16.1.45", "description": "Prevent violence"},
            {"indicator_no": "16.1.46", "description": "Psychological abuse"},
            {"indicator_no": "16.1.47", "description": "Public policy"},
            {"indicator_no": "16.1.48", "description": "Quality of life"},
            {"indicator_no": "16.1.49", "description": "Representative decision-making"},
            {"indicator_no": "16.1.50", "description": "Rule of law"},
            {"indicator_no": "16.1.51", "description": "Security threats"},
            {"indicator_no": "16.1.52", "description": "Sexual abuse"},
            {"indicator_no": "16.1.53", "description": "Sexual violence"},
            {"indicator_no": "16.1.54", "description": "Stolen assets"},
            {"indicator_no": "16.1.55", "description": "Tax evasion"},
            {"indicator_no": "16.1.56", "description": "Theft"},
            {"indicator_no": "16.1.57", "description": "Torture"},
            {"indicator_no": "16.1.58", "description": "Trafficking"},
            {"indicator_no": "16.1.59", "description": "Transparency"},
            {"indicator_no": "16.1.60", "description": "Un-sentenced detainees"},
            {"indicator_no": "16.1.61", "description": "Unstable societies"},
            {"indicator_no": "16.1.62", "description": "Victims of violence"},
            {"indicator_no": "16.1.63", "description": "Violence"},
            {"indicator_no": "16.1.64", "description": "Violence against women and children"},
            {"indicator_no": "16.1.65", "description": "Violence rates"},
            {"indicator_no": "16.1.66", "description": "Weapon seizures"}
        ]
    },
    {
        "sdg_no": 17,
        "title": "Partnerships for the Goals",
        "content": "Strengthen the means of implementation and revitalize the global partnership for sustainable development.",
        "targets": [
            {"target_no": "17.1", "description": "Strengthen domestic resource mobilization, including through international support to developing countries, to improve domestic capacity for tax and other revenue collection."}
        ],
        "indicators": [
            {"indicator_no": "17.1.1", "description": "Capacity building"},
            {"indicator_no": "17.1.2", "description": "Civil society partnerships"},
            {"indicator_no": "17.1.3", "description": "Communication technologies"},
            {"indicator_no": "17.1.4", "description": "Debt sustainability"},
            {"indicator_no": "17.1.5", "description": "Development assistance"},
            {"indicator_no": "17.1.6", "description": "Disaggregated data"},
            {"indicator_no": "17.1.7", "description": "Doha Development Agenda"},
            {"indicator_no": "17.1.8", "description": "Entrepreneurship"},
            {"indicator_no": "17.1.9", "description": "Environmentally sound technologies"},
            {"indicator_no": "17.1.10", "description": "Foreign direct investments"},
            {"indicator_no": "17.1.11", "description": "Fostering innovation"},
            {"indicator_no": "17.1.12", "description": "Free trade"},
            {"indicator_no": "17.1.13", "description": "Fundamental principles of official statistics"},
            {"indicator_no": "17.1.14", "description": "Global partnership"},
            {"indicator_no": "17.1.15", "description": "Global partnership for sustainable development"},
            {"indicator_no": "17.1.16", "description": "Global stability"},
            {"indicator_no": "17.1.17", "description": "International aid"},
            {"indicator_no": "17.1.18", "description": "International cooperation"},
            {"indicator_no": "17.1.19", "description": "International population and housing census"},
            {"indicator_no": "17.1.20", "description": "International support"},
            {"indicator_no": "17.1.21", "description": "International support for developing countries"},
            {"indicator_no": "17.1.22", "description": "Knowledge sharing"},
            {"indicator_no": "17.1.23", "description": "Multi-stakeholder partnerships"},
            {"indicator_no": "17.1.24", "description": "Poverty eradication"},
            {"indicator_no": "17.1.25", "description": "Public-private partnerships"},
            {"indicator_no": "17.1.26", "description": "Science cooperation agreements"},
            {"indicator_no": "17.1.27", "description": "Technology cooperation agreements"},
            {"indicator_no": "17.1.28", "description": "Technology transfer"},
            {"indicator_no": "17.1.29", "description": "Weighted tariff average"},
            {"indicator_no": "17.1.30", "description": "Women entrepreneurs"},
            {"indicator_no": "17.1.31", "description": "World Trade Organization"}
        ]
    }
]


def prepare_sdg_texts(sdg_data):
    texts = []
    meta = []
    for sdg in sdg_data:
        texts.append(f"SDG {sdg['sdg_no']} {sdg['title']} {sdg['content']}")
        meta.append({"level": "goal", "sdg_no": sdg["sdg_no"], "title": sdg["title"]})

        for target in sdg.get("targets", []):
            texts.append(f"SDG {sdg['sdg_no']} Target {target['target_no']} {target['description']}")
            meta.append({"level": "target", "sdg_no": sdg["sdg_no"], "target_no": target["target_no"]})

        for indicator in sdg.get("indicators", []):
            print(indicator)
            print(indicator['description'])
            texts.append(f"SDG {sdg['sdg_no']} Indicator {indicator['indicator_no']} {indicator['description']}")
            meta.append({"level": "indicator", "sdg_no": sdg["sdg_no"], "indicator_no": indicator["indicator_no"]})

    return texts, meta

# Load model
@st.cache_resource
def load_model():
    return SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

# Embed SDG data
@st.cache_resource
def compute_sdg_embeddings(texts, model):
    return model.encode(texts, convert_to_numpy=True, normalize_embeddings=True)

# Main app
st.title("🌱 SDG Context Analysis Tool")
st.write("Analyze your text against SDG goals, targets, and indicators.")

query = st.text_area("Enter your text:", height=150)
top_n = st.slider("Number of top matches", 1, 10, 3)
threshold = st.slider("Minimum similarity threshold", 0.0, 1.0, 0.5, 0.01)

if query and st.button("Analyze"):
    with st.spinner("Processing..."):
        model = load_model()
        texts, meta = prepare_sdg_texts(sdg_data)
        sdg_embeddings = compute_sdg_embeddings(texts, model)
        query_emb = model.encode(query, convert_to_numpy=True, normalize_embeddings=True)

        similarities = np.dot(sdg_embeddings, query_emb)
        sorted_idx = np.argsort(similarities)[::-1]
        
        results = []
        for idx in sorted_idx[:top_n]:
            if similarities[idx] < threshold:
                continue
            entry = meta[idx].copy()
            entry["text"] = texts[idx]
            entry["similarity"] = round(float(similarities[idx]), 3)
            results.append(entry)

    if results:
        st.success("Analysis complete!")
        for r in results:
            st.markdown(f"**{r['level'].capitalize()}**: SDG {r['sdg_no']}" +
                        (f" Target {r.get('target_no')}" if r['level'] == "target" else "") +
                        (f" Indicator {r.get('indicator_no')}" if r['level'] == "indicator" else "") +
                        f" — *{r.get('title', '')}*")
            st.markdown(f"Similarity: `{r['similarity']}`")
            st.markdown(f"Text: {r['text']}")
            st.markdown("---")
        
        # Export options
        df = pd.DataFrame(results)
        st.download_button("Download CSV", df.to_csv(index=False).encode('utf-8'), file_name="sdg_results.csv")
        st.download_button("Download JSON", json.dumps(results, indent=2).encode('utf-8'), file_name="sdg_results.json")
    else:
        st.warning("No matches above the threshold found.")

